### ISSUE TITLE
Umbrella projects

### ISSUE THREAD

**Issue by jayceekay** [andyl/vim-projectionist-elixir#2]
the config doesn't seem to work with umbrella projects. i just get `No alternate file`. any ideas?

tried editing projections.json to this:
```
{
  "apps/*/lib/*/*.ex": {
    "type":      "src",
    "alternate": "apps/*/test/*/*_test.exs"
  },
  "apps/*/test/*/*_test.exs": {
    "type":      "test",
    "alternate": "apps/*/lib/*/*.ex"
  }
}
```

**Comment by andyl** [comment]
Turns out the umbrella structure doesn't work out-of-the-box with vim-projectionist.  VP allows one wildcard expression in the path, and umbrella apps require two.

Best solution I think is to write a customized 'onload' vim function that generates an JSON or vim dict on the fly that merges all the app directories. (detail TBD)

**Comment by andyl** [comment]
A quick-and-dirty workaround is to add a `.projections.json` file to the home directory of your umbrella project...

**Comment by andyl** [comment]
I wrote a script to generate a `.projections.json` file - the project is at https://github.com/andyl/ex_projections.  Marking this issue closed.
